/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package liorh.dwkotlin

import com.fasterxml.jackson.databind.DeserializationFeature
import com.fasterxml.jackson.databind.SerializationFeature
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule
import com.fasterxml.jackson.module.kotlin.registerKotlinModule
import io.dropwizard.Application
import io.dropwizard.configuration.EnvironmentVariableSubstitutor
import io.dropwizard.configuration.ResourceConfigurationSourceProvider
import io.dropwizard.configuration.SubstitutingSourceProvider
import io.dropwizard.setup.Bootstrap
import io.dropwizard.setup.Environment
import org.eclipse.jetty.server.session.SessionHandler

class App : Application<AppConfig>() {

    override fun initialize(bootstrap: Bootstrap<AppConfig>) {
        super.initialize(bootstrap)
        configureObjectMapper(bootstrap)
        bootstrap.configurationSourceProvider = SubstitutingSourceProvider(ResourceConfigurationSourceProvider(), EnvironmentVariableSubstitutor(false))

    }

    override fun run(configuration: AppConfig, environment: Environment) {
        environment.servlets().setSessionHandler(SessionHandler())
    }

    private fun configureObjectMapper(bootstrap: Bootstrap<*>) {
        bootstrap.objectMapper.registerKotlinModule()
                .registerModule(Jdk8Module())
                .registerModule(JavaTimeModule())
                .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
                .configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false)

    }
}

fun main(args: Array<String>) {
    App().run(*args)
}
